"""
Django settings for final_project project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1-%_x^djymtfic_kls_d*t9-uxkue-dyf11qk++!itu0w6iuup'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'drf_yasg',
    'djangoviz'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'final_project.urls'

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",  # or another light theme
    "dark_mode_theme": "superhero",  # or another dark theme
    "accent": "accent-lightblue",
    "navbar": "navbar-light navbar-lightblue",
    "sidebar": "sidebar-dark-blue",
    "brand_colour": "navbar-lightblue",
    "sidebar_fixed": True,
    "grid_gutter_width": "20px",
    "body_small_text": False,
    "navbar_small_text": False,
    "sidebar_small_text": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_animation_speed": 300,
    "button_classes": {
        "primary": "btn-outline-lightblue",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success"
    },
    "actions_sticky_top": True,
}

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "Админстрация",
    "site_header": "Панель управления",
    "site_brand": "Админстрация",
    "site_logo_classes": "img-circle",
    "welcome_sign": "Добро пожаловать в Центр управления",
    "copyright": "Cloud APP © 2024 | Powering the Future of Bots",
    "search_model": ["api.Users", ],
    "user_avatar": "avatar",
    "topmenu_links": [
        {"name": "Домой", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "api.Bots"},
        {"model": "api.Chats"},
        {"model": "api.Wappi"},
    ],
    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "api"],
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user-astronaut",
        "auth.Group": "fas fa-users",
        "api.User": "fas fa-user",
        "api.Event": "fas fa-calendar",
        "api.Registration": "fas fa-user-plus",
        "api.Notification": "fas fa-bell",
        "api.Payment": "fas fa-money-bill",
        "api.Venue": "fas fa-map-marker-alt",
        "api.Ticket": "fas fa-ticket-alt",
        "api.Review": "fas fa-star",
        "api.Category": "fas fa-list",
        "api.EventCategory": "fas fa-list-alt",
    },
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    "search_bar": True,
    "usermenu_links": [
        {"name": "Support", "url": "https://support.cloud.com", "icon": "fas fa-life-ring"},
        {"model": "auth.user"}
    ],
    "show_ui_builder": True,
    "css_variables": {
        "primary": "#009688",  # Teal
        "secondary": "#607D8B",  # Blue Grey
        "accent": "#4DB6AC",  # Light Teal
        "primary-fg": "#ffffff",
        "secondary-fg": "#ffffff",
        "accent-fg": "#ffffff",
    }
}



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'final_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CSRF_TRUSTED_ORIGINS = ['https://localhost:8000', 'https://0.0.0.0:8000']

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
